// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(HubClienteContext))]
    [Migration("20250523184542_AdicionadoEntidadeEndereco")]
    partial class AdicionadoEntidadeEndereco
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Entities.Cliente", b =>
                {
                    b.Property<Guid>("CodigoCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("codigo_cliente");

                    b.Property<string>("CepCliente")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cep_cliente");

                    b.Property<string>("EmailCliente")
                        .HasColumnType("text")
                        .HasColumnName("email_cliente");

                    b.Property<string>("NomeCliente")
                        .HasColumnType("text")
                        .HasColumnName("nome_cliente");

                    b.HasKey("CodigoCliente");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("Domain.Models.Entities.Endereco", b =>
                {
                    b.Property<Guid>("CodigoEndereco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("codigo_endereco");

                    b.Property<string>("Bairro")
                        .HasColumnType("text")
                        .HasColumnName("bairro");

                    b.Property<Guid>("CodigoCliente")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Complemento")
                        .HasColumnType("text")
                        .HasColumnName("complemento");

                    b.Property<string>("Localidade")
                        .HasColumnType("text")
                        .HasColumnName("localidade");

                    b.Property<string>("Logradouro")
                        .HasColumnType("text")
                        .HasColumnName("logradouro");

                    b.Property<string>("Uf")
                        .HasColumnType("text")
                        .HasColumnName("uf");

                    b.HasKey("CodigoEndereco");

                    b.HasIndex("CodigoCliente")
                        .IsUnique();

                    b.ToTable("endereco");
                });

            modelBuilder.Entity("Domain.Models.Entities.Endereco", b =>
                {
                    b.HasOne("Domain.Models.Entities.Cliente", "Cliente")
                        .WithOne("Endereco")
                        .HasForeignKey("Domain.Models.Entities.Endereco", "CodigoCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Domain.Models.Entities.Cliente", b =>
                {
                    b.Navigation("Endereco");
                });
#pragma warning restore 612, 618
        }
    }
}
