// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(HubClienteContext))]
    [Migration("20250521185527_TabelaCliente")]
    partial class TabelaCliente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("CodigoCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("codigo_cliente");

                    b.Property<string>("CepCliente")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cep_cliente");

                    b.Property<string>("EmailCliente")
                        .HasColumnType("text")
                        .HasColumnName("email_cliente");

                    b.Property<string>("NomeCliente")
                        .HasColumnType("text")
                        .HasColumnName("nome_cliente");

                    b.HasKey("CodigoCliente");

                    b.ToTable("clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
